---
title: "HW1 STAA 566"
author: "Claudia Santillan-Lensink"
date: "2/2/2022"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
  encoding=encoding,
  output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(viridisLite)
library(viridis)
```


```{r readindata}
bostonmarathon <- read.csv("DatasetBoston2019.csv")
#head(bostonmarathon)

most_boston <- bostonmarathon %>% count(Country, sort=TRUE)
most_boston <- most_boston[1:7,]
#most_boston
most_countries <- c(most_boston[,1])
#most_countries

pbos <- bostonmarathon %>% 
  filter(Country %in% most_countries) %>%
  ggplot(aes(x=Age,
             y=(Result_sec/3600),
             color = Country)) +
  geom_point(alpha = 0.03) +
  theme_tufte(base_size = 10, base_family = "sans") +
  scale_color_viridis(discrete = TRUE) +
  ylab("Finish Time (hours)") +
  xlab("Age (Years)") +
  stat_smooth(alpha = 0.25, method = "loess") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("2019 Boston Marathon Finishing Times by Age\nTop Ten Participating Countries")
pbos

pdf("bostonmarathon2019.pdf", height=4, width=6)
print(pbos)
dev.off()
```

